export enum TreeBuildMode {
    Initial = "Initial",
    BeforeHtml = "BeforeHtml",
    BeforeHead = "BeforeHead",
    InHead = "InHead",
    InHeadNoscript = "InHeadNoscript",
    AfterHead = "AfterHead",
    InBody = "InBody",
    Text = "Text",
    InTable = "InTable",
    InTableText = "InTableText",
    InCaption = "InCaption",
    InColumnGroup = "InColumnGroup",
    InTableBody = "InTableBody",
    InRow = "InRow",
    InCell = "InCell",
    InSelect = "InSelect",
    InSelectInTable = "InSelectInTable",
    InTemplate = "InTemplate",
    AfterBody = "AfterBody",
    InFrameset = "InFrameset",
    AfterFrameset = "AfterFrameset",
    AfterAfterBody= "AfterAfterBody",
    AfterAfterFrameset = "AfterAfterFrameset",
}